# Import useful libraries

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score

# Reading the Titanic Training Dataset

In [6]:
df = pd.read_csv('C:/Users/Vishal/Desktop/LU aiml/Data/Titanic training dataset.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
lab = LabelEncoder()

df["Sex"] = lab.fit_transform(df["Sex"])
df["Embarked"] = lab.fit_transform(df["Embarked"])

In [8]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

# Checking Null Values

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

# dropping irrelevent columns

In [10]:
df1=df.drop(['Cabin','PassengerId','Name','Ticket'],axis=1)
df1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [25]:
def prediction(col):
    
    clf = svm.SVC(gamma = 0.01, C = 100)
    acc=[]
    for i in col:
        x = df1.drop([i], axis=1)
        print("====================================================================")
        print(f"The Dependent Variable is {i} & remaining are Independent Variables")
        y = df1[i]
    
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.3, random_state=0)
        support = clf.fit(x_train,y_train)
        ypred = support.predict(x_test)
        scored=accuracy_score(y_test, ypred, normalize=True)
        print(f"\n Acuuracy Score for {i} is: ", accuracy_score(y_test, ypred, normalize=True))
        acc.append(scored)
        print(f"\n Confusion matrix for {i} is \n", confusion_matrix(y_test, ypred))
    return acc


In [26]:
c = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch','Embarked']        
prediction(c)

The Dependent Variable is Survived & remaining are Independent Variables

 Acuuracy Score for Survived is:  0.7415730337078652

 Confusion matrix for Survived is 
 [[124  33]
 [ 36  74]]
The Dependent Variable is Pclass & remaining are Independent Variables

 Acuuracy Score for Pclass is:  0.9026217228464419

 Confusion matrix for Pclass is 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
The Dependent Variable is Sex & remaining are Independent Variables

 Acuuracy Score for Sex is:  0.7265917602996255

 Confusion matrix for Sex is 
 [[ 66  32]
 [ 41 128]]
The Dependent Variable is SibSp & remaining are Independent Variables

 Acuuracy Score for SibSp is:  0.7490636704119851

 Confusion matrix for SibSp is 
 [[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
 [  0   2   1   3   1   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
The Dependent Variable is Parch & remaining are Independent Vari

[0.7415730337078652,
 0.9026217228464419,
 0.7265917602996255,
 0.7490636704119851,
 0.797752808988764,
 0.7677902621722846]

# Inference:

The Pclass as a dependent variable and remaining as Independent variable has the highest accuracy score.