<a href="https://colab.research.google.com/github/ankush2610/LetsUpgrade-AI-ML/blob/master/day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [10]:
a=np.random.random((3,3,3))
a

array([[[0.23404312, 0.62403464, 0.64583908],
        [0.08981964, 0.41276654, 0.88332072],
        [0.96564214, 0.0379574 , 0.03465409]],

       [[0.00865603, 0.51073973, 0.60283382],
        [0.29499908, 0.41009525, 0.90682762],
        [0.96031201, 0.06759395, 0.65277639]],

       [[0.07806594, 0.37870419, 0.32805552],
        [0.60795105, 0.2771721 , 0.31580835],
        [0.45166737, 0.35567176, 0.50000828]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
b=np.zeros((5,5),dtype=int)
for i in range(1,5):
  b[i:,i-1]=i

"""
ANOTHER METHOD
b[1:,0]=1
b[2:,1]=2
b[3:,2]=3
b[4:,3]=4
"""
b

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 2, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 2, 3, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
import numpy as np

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [38]:
import numpy as np
norm= np.arange(1,101,4).reshape(5,5)

print("Initial Array:")
print(norm)
max, min = norm.max(), norm.min()
norm = (norm - min)/(max - min)
print("After normalization:")
print(norm)

Initial Array:
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]
After normalization:
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


# 5.  How to find common values between two arrays?

In [40]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
print("Common values are:")
print(np.intersect1d(array1, array2))

Common values are:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [48]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [52]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 0 1 0]
Second array:
[0 1 1 0 1 0]
Test above two arrays are equal or not!
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [87]:
b=np.array([35,44,646,535,35,32,353,535,33,3])
b.size
mx=b.max()
mx
f=np.where(b==mx)
b[f]=0
print(b)

#ALTERNATE METHOD

#b[b.argmax()]=0
#b


[ 35  44   0 535  35  32 353 535  33   3]


# 9. How to print all the values of an array?

In [93]:
a=np.random.random((2,2,2))
a


array([[[0.03104127, 0.72696729],
        [0.87998127, 0.66942233]],

       [[0.59603549, 0.70744624],
        [0.03755782, 0.73574777]]])

# 10.Subtract the mean of each row of a matrix

In [94]:
c = np.array([[[0,1,2], [2,2,3], [2,2,3]], [[3,4,5], [6,5,7], [2,2,3]]])

sub = c - c.mean(axis=1, keepdims=True)
print(sub)

[[[-1.33333333 -0.66666667 -0.66666667]
  [ 0.66666667  0.33333333  0.33333333]
  [ 0.66666667  0.33333333  0.33333333]]

 [[-0.66666667  0.33333333  0.        ]
  [ 2.33333333  1.33333333  2.        ]
  [-1.66666667 -1.66666667 -2.        ]]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [100]:
c = np.array([[[0,1,2], [2,2,3], [2,2,3]], [[3,4,5], [6,5,7], [2,2,3]]])
b=np.ones((2,3,3))
c=c+b
c

array([[[1., 2., 3.],
        [3., 3., 4.],
        [3., 3., 4.]],

       [[4., 5., 6.],
        [7., 6., 8.],
        [3., 3., 4.]]])

# 12.How to get the diagonal of a dot product?

In [105]:
a = np.ones((4, 3))
b=np.array([[0,1,2], [2,2,3], [2,2,3]])
dot=a.dot(b)
np.diag(dot)

array([4., 5., 8.])

# 13.How to find the most frequent value in an array?

In [110]:
x = np.random.randint(0, 10, 30)
print("Original array:")
print(x)
print("Most repeated value in the array:",np.bincount(x).argmax())


Original array:
[0 7 7 5 1 8 8 7 0 8 8 8 6 4 9 8 7 2 1 5 9 5 0 9 0 5 3 9 5 7]
Most repeated value in the array: 8


# 14.How to get the n largest values of an array


In [115]:
x = np.arange(10)


np.random.shuffle(x)
n = 3
print (x[np.argsort(x)[-n:]])

[7 8 9]


# 15.How to create a record array from a regular array?

In [120]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
recor= np.core.records.fromarrays([a1, a2, a3])
print(recor[0])
print(recor[3])

(1, 'Red', 12.2)
(4, 'Orange', 40.)
